[features]
seeds = false
skip-lint = false
[programs.localnet]
tweeter_app_solana_program = "ARVmA87wQaxWkstZksLnmcjLmUhHbYYyJF6SNmWX1Cqk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jeecode/.config/solana/jayson-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
